[package]
name = "due-blink"
version = "0.1.0"
authors = ["Krzysztof Langner <klangner@gmail.com>"]


[dependencies]


[profile.release]
# Add link-time optimization to minimize the code size.
lto = true